# Generated by Django 2.2.16 on 2022-10-27 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20221025_0044'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='reviews',
            new_name='review',
        ),
    ]
